runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: main.app

- url: /
  static_files: static/index.htm
  upload: static/index.htm

- url: /([^.]*)
  static_files: static/\1.htm
  upload: static/(.*)

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
