runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  secure: always
  script: main.app

- url: /
  secure: always
  static_files: guerilla-gifts/platforms/browser/www/index.html
  upload: guerilla-gifts/platforms/browser/www/index.html

- url: /(.*)
  secure: always
  static_files: guerilla-gifts/platforms/browser/www/\1
  upload: guerilla-gifts/platforms/browser/www/(.*)
